mini_second/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/urls.py
from django.urls import path
from . import views

app_name = 'webapp'
urlpatterns = [
   # path('', views.index),
   path('', views.PostList.as_view(), name='index'),
   path('createform/', views.createform, name='createform'),
   path('logout/', views.logout, name='logout'),
   path('signin/', views.signin, name='login'),
   path('delete/<int:pk>/', views.data_delete, name='delete'),
]

webapp/models.py
from django.db import models


class Info(models.Model):
   FIRMV_2_32 = 'r1m_v2.32'
   FIRMV_CHOICE = (
      (FIRMV_2_32, 'r1m_v2.32'),
   )

   battery = models.CharField(max_length=30)
   color =  models.CharField(max_length=30, default=0)
   runtime = models.CharField(null=True, max_length=30)
   firmV = models.CharField(choices=FIRMV_CHOICE, max_length=20,default=FIRMV_2_32)

   created_at = models.DateTimeField(auto_now=True)

   updated_at = models.DateTimeField(auto_now=True)

   def __str__(self):
      return f'[{self.pk}] bat : {self.battery}% / runtime : {self.runtime}ms'

webapp/views.py
from django.contrib import auth
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect, get_object_or_404
from .models import Info
from django.views.generic import ListView


# Create your views here.


class PostList(ListView):
    model = Info
    ordering = '-pk'


def createform(request):
    std = Info()
    std.battery = request.GET['battery']
    std.color = request.GET['color']
    std.runtime = request.GET['runtime']
    std.firmV = request.GET['firmV']
    std.save()
    return redirect('/')


def data_delete(request, pk):
    del_data = get_object_or_404(Info, pk=pk)
    del_data.delete()
    std = Info.objects.all().order_by('-pk')
    return redirect('/', {
        'std': std
    })


def signin(request):
    if request.method == "GET":
        return redirect('webapp:index')

    elif request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('webapp:index')
        else:
            return redirect('webapp:index')


def logout(request):
    if request.method == 'POST':
        auth.logout(request)
    return redirect('webapp:index')

webapp/templates/webapp/html/accordion.html
<!-- accordion -->
<div class="container">
    <div class="section-title">
        <p>지난 기록들을 확인할 수 있습니다.</p>
    </div>
    <div class="text-center">
        <form action="" id="setRows">
            <input type="text" name="rowPerPage" value="7">
        </form>
        <button id="btn-all-close">ALL Close</button>
    </div>
    <br>
    <table class="table table-bordered table-striped table-hover data_review">
        <thead class="thead-light text-center">
        <th id="thText">날짜를 클릭해주세요.</th>
        </thead>
        <tbody id="products" class="text-center">
        {% for s in info_list %}
        <tr>
            <td>
                <div class="panel-faq-container review_data">
                    <p class="panel-faq-title">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;{{ s.created_at }}</p>
                    </h5>
                    <div class="panel-faq-answer">
                        <div class="col-md-3 info_review">배터리 : {{ s.battery }}%</div>
                        <div class="col-md-4 info_review" id="accor_runtime">구동 시간 : {{ s.runtime }}</div>
                        <div class="col-md-3 info_review">
                            LED : <input class="color_box_inputs" type="color" value="{{ s.color }}" disabled/>
                        </div>
                        <div class="col-md-2 info_review">
                            <a href="{% url 'webapp:delete' s.pk %}">기록 삭제</a>
                        </div>
                        </p>
                    </div>
                </div>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
    <div id="review_nav"></div>
</div>
<!-- End accordion section -->

webapp/templates/webapp/html/contact.html
<!-- ======= Contact Section ======= -->
<section id="contact" class="contact">
    <div class="container">

        <div class="section-title">
            <h2>Contact</h2>
            <h3>Contact <span>Us</span></h3>
            <p>Ut possimus qui ut temporibus culpa velit eveniet modi omnis est adipisci expedita at voluptas atque
                vitae
                autem.</p>
        </div>

        <div>
            <iframe style="border:0; width: 100%; height: 270px;"
                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3213.508152389766!2d127.3800007153575!3d36.34846858004409!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x35654be1d22851ad%3A0xf50f267c3c4519dd!2z66-4656Y7Jy17ZWp6rWQ7Jyh7JuQ!5e0!3m2!1sko!2skr!4v1674145724710!5m2!1sko!2skr"
                    frameborder="0" allowfullscreen></iframe>
        </div>

        <div class="row mt-5">

            <div class="col-lg-4">
                <div class="info">
                    <div class="address">
                        <i class="bi bi-geo-alt"></i>
                        <h4>Location:</h4>
                        <p>A108 Adam Street, New York, NY 535022</p>
                    </div>

                    <div class="email">
                        <i class="bi bi-envelope"></i>
                        <h4>Email:</h4>
                        <p>info@example.com</p>
                    </div>

                    <div class="phone">
                        <i class="bi bi-phone"></i>
                        <h4>Call:</h4>
                        <p>+1 5589 55488 55s</p>
                    </div>

                </div>

            </div>

            <div class="col-lg-8 mt-5 mt-lg-0">

                <form action="forms/contact.php" method="post" role="form" class="php-email-form">
                    <div class="row">
                        <div class="col-md-6 form-group">
                            <input type="text" name="name" class="form-control" id="name" placeholder="Your Name"
                                   required>
                        </div>
                        <div class="col-md-6 form-group mt-3 mt-md-0">
                            <input type="email" class="form-control" name="email" id="email"
                                   placeholder="Your Email" required>
                        </div>
                    </div>
                    <div class="form-group mt-3">
                        <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject"
                               required>
                    </div>
                    <div class="form-group mt-3">
                            <textarea class="form-control" name="message" rows="5" placeholder="Message"
                                      required></textarea>
                    </div>
                    <div class="my-3">
                        <div class="loading">Loading</div>
                        <div class="error-message"></div>
                        <div class="sent-message">Your message has been sent. Thank you!</div>
                    </div>
                    <div class="text-center">
                        <button type="submit">Send Message</button>
                    </div>
                </form>

            </div>

        </div>

    </div>
</section><!-- End Contact Section -->

webapp/templates/webapp/html/cta.html
<!-- ======= Cta Section ======= -->
<section id="cta" class="cta">
    <div class="container">

        <div class="text-center">
            <h3>Call To Action</h3>
            <p> Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla
                pariatur.
                Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id
                est
                laborum.</p>
            <a class="cta-btn" href="#">Call To Action</a>
        </div>


    </div>
</section><!-- End Cta Section -->

webapp/templates/webapp/html/faq.html
<!-- ======= F.A.Q Section ======= -->
<section id="faq" class="faq">
    <div class="container">

        <div class="section-title">
            <h2>F.A.Q</h2>
            <h3>Frequently Asked <span>Questions</span></h3>
        </div>

        <ul class="faq-list">

            <li>
                <div data-bs-toggle="collapse" class="collapsed question" href="#faq1">Non consectetur a erat nam at
                    lectus
                    urna duis? <i class="bi bi-chevron-down icon-show"></i><i
                            class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq1" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Feugiat pretium nibh ipsum consequat. Tempus iaculis urna id volutpat lacus laoreet non
                        curabitur
                        gravida. Venenatis lectus magna fringilla urna porttitor rhoncus dolor purus non.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq2" class="collapsed question">Feugiat scelerisque varius
                    morbi enim
                    nunc faucibus a pellentesque? <i class="bi bi-chevron-down icon-show"></i><i
                            class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq2" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit
                        laoreet id
                        donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est
                        pellentesque elit
                        ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq3" class="collapsed question">Dolor sit amet consectetur
                    adipiscing
                    elit pellentesque habitant morbi? <i class="bi bi-chevron-down icon-show"></i><i
                            class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq3" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Eleifend mi in nulla posuere sollicitudin aliquam ultrices sagittis orci. Faucibus pulvinar
                        elementum
                        integer enim. Sem nulla pharetra diam sit amet nisl suscipit. Rutrum tellus pellentesque eu
                        tincidunt.
                        Lectus urna duis convallis convallis tellus. Urna molestie at elementum eu facilisis sed
                        odio morbi quis
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq4" class="collapsed question">Ac odio tempor orci dapibus.
                    Aliquam
                    eleifend mi in nulla? <i class="bi bi-chevron-down icon-show"></i><i
                            class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq4" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Dolor sit amet consectetur adipiscing elit pellentesque habitant morbi. Id interdum velit
                        laoreet id
                        donec ultrices. Fringilla phasellus faucibus scelerisque eleifend donec pretium. Est
                        pellentesque elit
                        ullamcorper dignissim. Mauris ultrices eros in cursus turpis massa tincidunt dui.
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq5" class="collapsed question">Tempus quam pellentesque nec
                    nam
                    aliquam sem et tortor consequat? <i class="bi bi-chevron-down icon-show"></i><i
                            class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq5" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Molestie a iaculis at erat pellentesque adipiscing commodo. Dignissim suspendisse in est
                        ante in. Nunc
                        vel risus commodo viverra maecenas accumsan. Sit amet nisl suscipit adipiscing bibendum est.
                        Purus
                        gravida quis blandit turpis cursus in
                    </p>
                </div>
            </li>

            <li>
                <div data-bs-toggle="collapse" href="#faq6" class="collapsed question">Tortor vitae purus faucibus
                    ornare.
                    Varius vel pharetra vel turpis nunc eget lorem dolor? <i
                            class="bi bi-chevron-down icon-show"></i><i
                            class="bi bi-chevron-up icon-close"></i></div>
                <div id="faq6" class="collapse" data-bs-parent=".faq-list">
                    <p>
                        Laoreet sit amet cursus sit amet dictum sit amet justo. Mauris vitae ultricies leo integer
                        malesuada
                        nunc vel. Tincidunt eget nullam non nisi est sit amet. Turpis nunc eget lorem dolor sed. Ut
                        venenatis
                        tellus in metus vulputate eu scelerisque. Pellentesque diam volutpat commodo sed egestas
                        egestas
                        fringilla phasellus faucibus. Nibh tellus molestie nunc non blandit massa enim nec.
                    </p>
                </div>
            </li>

        </ul>

    </div>
</section><!-- End F.A.Q Section -->

webapp/templates/webapp/html/footer.html
<!-- ======= Footer ======= -->
<footer id="footer">

    <div class="footer-top">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-md-6 footer-contact">
                    <h3>Tempo</h3>
                    <p>
                        A108 Adam Street <br>
                        New York, NY 535022<br>
                        United States <br><br>
                        <strong>Phone:</strong> +1 5589 55488 55<br>
                        <strong>Email:</strong> info@example.com<br>
                    </p>
                </div>

                <div class="col-lg-2 col-md-6 footer-links">
                    <h4>Useful Links</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Home</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">About us</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Services</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Terms of service</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Privacy policy</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-md-6 footer-links">
                    <h4>Our Services</h4>
                    <ul>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Design</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Web Development</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Product Management</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Marketing</a></li>
                        <li><i class="bx bx-chevron-right"></i> <a href="#">Graphic Design</a></li>
                    </ul>
                </div>

                <div class="col-lg-4 col-md-6 footer-newsletter">
                    <h4>Join Our Newsletter</h4>
                    <p>Tamen quem nulla quae legam multos aute sint culpa legam noster magna</p>
                    <form action="" method="post">
                        <input type="email" name="email"><input type="submit" value="Subscribe">
                    </form>
                </div>

            </div>
        </div>
    </div>

    <div class="container d-md-flex py-4">

        <div class="me-md-auto text-center text-md-start">
            <div class="copyright">
                &copy; Copyright <strong><span>Tempo</span></strong>. All Rights Reserved
            </div>
            <div class="credits">
                <!-- All the links in the footer should remain intact. -->
                <!-- You can delete the links only if you purchased the pro version. -->
                <!-- Licensing information: https://bootstrapmade.com/license/ -->
                <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/tempo-free-onepage-bootstrap-theme/ -->
                Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
            </div>
        </div>
        <div class="social-links text-center text-md-right pt-3 pt-md-0">
            <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
            <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
            <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
            <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
            <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
        </div>
    </div>
</footer><!-- End Footer -->

<a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i
        class="bi bi-arrow-up-short"></i></a>

webapp/templates/webapp/html/hero.html
<!-- ======= Hero Section ======= -->
{% load static %}
<section id="hero" class="carousel slide" data-bs-ride="carousel">

    <div class="carousel-inner" style="filter: brightness(50%); width: 100%; height: 100vh;">
        <div class="carousel-item active">
            <img src="{% static 'webapp/assets/img/hero-bg.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'webapp/assets/img/R1mini-bg.jpg' %}" class="d-block w-100" alt="...">
        </div>
        <div class="carousel-item">
            <img src="{% static 'webapp/assets/img/cta-bg.jpg' %}" class="d-block w-100" alt="...">
        </div>
    </div>

    <div class="hero-container">
        <h3>Welcome to <strong>OMOROBOT</strong></h3>
        <h1>OMO R1MINI</h1>
        <h2>초급자부터 전문가까지 한 대의 로봇으로 지속하는 자율주행 연구.</h2>
        <a href="#about" class="btn-get-started scrollto">Get Started</a>
    </div>

</section>
<!-- End Hero -->

webapp/templates/webapp/html/login_temp.html
<!-- Login modal -->
<div class="modal fade" id="loginModal" tabindex="-1" role="dialog" aria-labelledby="loginModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="loginModalLabel">Log In</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body logmodalbody">
                <div>
                    {% load static %}
                    <div class="signin_temp">
                        <div class="signin_form">
                            <div class="signin_img_box">
                                <img class="signin_img" src="{% static 'webapp/assets/img/login.jpg' %}">
                            </div>
                            <form action="{% url 'webapp:login' %}" method="post" class="login_form">{% csrf_token %}
                                <div class="signin_input">
                                    <div class="signin_username">
                                        <div class="signin_username_con">
                                            <span class="signin_icon"><i class="fa-regular fa-user"></i></span>
                                            <input type="input" name="username" placeholder="UserName"
                                                   class="username_input">
                                        </div>
                                    </div>
                                    <div class="signin_passward">
                                        <div class="signin_passward_con">
                                            <span class="signin_icon"><i class="fa-solid fa-lock"></i></span>
                                            <input type="password" name="password" placeholder="PassWord"
                                                   class="passward_input">
                                        </div>
                                    </div>
                                </div>
                                <div class="signin_btn">
                                    <input type="submit" value="Login" class="signin_btn1">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

webapp/templates/webapp/html/logout_temp.html
<!-- Logout modal -->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="logoutModalLabel"
     aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logoutModalLabel">Log Out</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="logoutmodalbody">
                <div class="logout_temp"></div>
                <div id="logout_tdiv"><h3 id="logout_text">로그아웃 되었습니다.</h3></div>
            </div>
            <div class="modal-footer">
                <form action="{% url 'webapp:logout' %}" method="post" class="col-md-4 logout_button">
                    {% csrf_token %}
                    <input type="submit" value="확인">
                </form>
            </div>
        </div>
    </div>
</div>

webapp/templates/webapp/html/omo_edit.html
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">정보 입력</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="{% url 'webapp:createform' %}" class="robot_input">
                    <div class="modalForm">
                        <div>
                            <div>
                                배터리<input type="text" name="battery" id="batteryInput">
                            </div>
                            <br>
                            <div>
                                경과 시간<input type="text" name="runtime" id="runtimeInput">
                            </div>
                            <br>
                            <div>
                                색상<input type="color" name="color" id="colorInput">
                            </div>
                            <br>
                            <div>
                                펌웨어 버전
                                <select name="firmV">
                                    <option>r1m_v2.32</option>
                                </select>
                            </div>
                        </div>

                        <div class="buttonArea">
                            <div>
                                <button type="submit" class="btn btn-secondary">입력</button>
                            </div>
                            <div class="inputButton">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">취소</button>
                            </div>
                        </div>
                    </div>
                </form>

            </div>

        </div>
    </div>
</div>

webapp/templates/webapp/html/test.html
<!-- 실험용 html 코드 -->

webapp/templates/webapp/info_review.html
<section id="about_list" class="about_list">
    <div class="container">
        <div class="section-title">
            <h2>Info</h2>
            <h3>OMO R1MINI <span>데이터 조회</span></h3>
            <p>데이터 정보를 조회할 수 있습니다.</p>
        </div>
        <div class="row content">
          <div class="section-title">

            <!-- Project Card Example -->
            {% if info_list %}
            {% for p in info_list %}
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <div class="infoarea">
                  <h6 class="m-0 font-weight-bold text-primary infoTITLE">INFO</h6>

        {% if is_paginated %}
          <ul class="pagination justify-content-center my-4">
              {% if page_obj.has_previous %}
              <li class="page-item">
                  <a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; Newer</a>
              </li>
              {% else %}
              <li class="page-item disabled">
                  <a class="page-link" href="#">&larr; Newer</a>
              </li>
              {% endif %}

              {% if page_obj.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ page_obj.next_page_number }}">Older &rarr;</a>
                </li>
              {% else %}
                <li class="page-item disabled">
                    <a class="page-link" href="#">Older &rarr;</a>
                </li>
              {% endif %}
          </ul>
            {% endif %}
                </div>
              </div>
              <div class="card-body">
                <div class="infoTop">
                  <div class="bat">
                    <h4 class="small font-weight-bold">BATTERY<span class="float-right bat_review">
                        {{ p.battery }}
                      </span></h4>
                    <div class="progress mb-4">
                      <div class="progress bat_prog_review" role="progressbar" aria-label="Animated striped example" aria-valuenow="20"
                        aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bat_prog_col_review" style="width: 100%"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                  <div class="infoBottom">
                    <div class="colInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold color_box_fig">COLOR<span class="float-right">

                        <div>
                          <input class="color_box_input" type="color" value="{{ p.color }}" disabled />
                        </div>
                        </span></h4>
                      </div>
                    </div>
                    <div class="runInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold runtime_fig">RUN TIME<span class="float-right bat-fig">

                      <div>
                        <h3 class="runtime_info">
                          {{ p.runtime }}
                        </h3>
                      </div>

                      </span></h4>
                      </div>
                    </div>
                    <div class="firmV mb-4">
                      <h4 class="small font-weight-bold firmV_fig">firmV<span class="float-right bat-fig">
                      <div>
                        <h3 class="firmV_info">
                          {{ p.firmV }}
                        </h3>
                      </div>
                      </span></h4>
                    </div>

                  </div>
                </div>
              </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="card shadow mb-4">
              <div class="card-header py-3">
                <div class="infoarea">
                  <h6 class="m-0 font-weight-bold text-primary infoTitle">INFO</h6>
                  {% if user.is_authenticated %}
                  <a href="" title="Button push blue/green" class="button btnPush btnBlueGreen" data-bs-toggle="modal"
                    data-bs-target="#exampleModal">INPUT</a>
                  {% endif %}

                </div>
              </div>
              <div class="card-body">
                <div class="infoTop">
                  <div class="bat">
                    <h4 class="small font-weight-bold">BATTERY<span class="float-right bat-fig" >
                        0
                      </span></h4>
                    <div class="progress mb-4">
                      <div class="progress bat-prog" role="progressbar" aria-label="Animated striped example" aria-valuenow="20"
                        aria-valuemin="0" aria-valuemax="100">
                        <div class="progress-bar progress-bar-striped progress-bar-animated bat_prog_col" style="width: 100%"></div>
                      </div>
                    </div>
                  </div>
                  <br>
                  <div class="infoBottom">
                    <div class="colInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold color_box_fig">COLOR<span class="float-right">

                        <div>
                          <input class="color_box_input" type="color" value="#000000" disabled />
                        </div>
                        </span></h4>
                      </div>
                    </div>
                    <div class="runInfo mb-4">
                      <div>
                        <h4 class="small font-weight-bold runtime_fig">RUN TIME<span class="float-right bat-fig">

                      <div>
                        <h3 class="runtime_info">
                          0
                        </h3>
                      </div>

                      </span></h4>
                      </div>
                    </div>
                    <div class="firmV mb-4">
                      <h4 class="small font-weight-bold firmV_fig">firmV<span class="float-right bat-fig">
                      <div>
                        <h3 >
                          NULL
                        </h3>
                      </div>
                      </span></h4>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {% endif %}
          </div>
        </div>

      </div>
            </section>